### ISSUE TITLE
unable to make the trusted ChatID Array in conf

### ISSUE THREAD

**Issue by ramalmaty** [ldrsousa/php-telegram-bot#1]
Good Day!

Thank you very much for the simple code.
I liked it very much, but only problem I face is I am unable to make the ChatID's check in config file for trusted ID's.

I have a column with chatID's which i want to add to the trusted variable.

May be I am doing it wrong or maybe some problem in the code. can you please assist me.

I used foreach to loop through the rows and tried to make it get in variable as print_r($ChatIDs);
but its not working that way

**Comment by ldrsousa** [comment]
Hello ramalmaty!

Thanks for appreciate my code!

To insert chat ID's in trusted variable, you need in the hook.php file,
after include_once "conf.php"; (line 11) rewrite the variable trusted from
conf.php file.

You can do this as follows:

$conf['trusted'] = []; // clear trusted conf array
foreach ($chat_ids as $chat_id) { // for all your chat ID's
    $conf['trusted'][] = $chat_id; // insert in trusted array
}

Hope you can make it works!

Regards

**Comment by ramalmaty** [comment]
Thank you very much for the fast reply Leandro.

I am trying it, may be my knowledge is not enough, I will post what I did and what i tested so far.

For Info I use, PHPMaker Generated files, that i included in the conf.php file.

[ewdbhelper12-php.txt](https://github.com/ldrsousa/php-telegram-bot/files/2180587/ewdbhelper12-php.txt)

Then I tried this in config.php file:

require_once ('../ewdbhelper13.php');
$db = &DbHelper();

$UsrSql = "SELECT ChatID FROM user WHERE CHATID != ''";
$ors = $db->LoadRecordset($UsrSql);
$OProws = $ors->GetRows();

foreach ($OProws as $r_v) {
$trust[] = $r_v["TbotCid"];
}
$trustme = implode(", ", $trust);

$conf = [
                //Change to your bot token, check the readme to know how to create and get your bot token.
                'bot_token' => 'BOT TOKEN',
                //Set to TRUE if you want the bot only to awnser the trusted ChatIDs
                'only_trusted' => TRUE,
                //Populate the array with the trusted Chat IDs
                'trusted' => [$trustme],
  
                ];

This seems to work but, only for 1st ID, not getting other ID's,

While i tired for inserting in truest variable with 2 ids comma separated, it works fine. so the problem seems getting the data in 'trusted' => [$trustme] is suffering

**Comment by ldrsousa** [comment]
Hello,

Try change this in $conf array:

'trusted' => [$trustme],
to
'trusted' => $trust,

You don't need the implode with commas.

If you want use the implode in the $conf array you need explode to generate
an array again
'trusted' => explode(", ", $trustme),

First option is more simple and fast! ;)

Regards

**Comment by ramalmaty** [comment]
Absolutely Right Leandro,

foreach ($OProws as $r_v) {
$trust[] = $r_v['TbotCid'];
}

$conf = [
                //Change to your bot token, check the readme to know how to create and get your bot token.
                'bot_token' => '<BOT TOKEN>',
                //Set to TRUE if you want the bot only to answer the trusted ChatIDs
                'only_trusted' => TRUE,
                //Populate the array with the trusted Chat IDs
                'trusted' => $trust,
                ];

Thank you very much, you saved my day!

Pasting the code here, if anyone need it.

I was having sleepless nights for a week to get it work.
